DELETE FROM Rider;
DELETE FROM Manager;
DELETE FROM WWS;
DELETE FROM WorkShift;
DELETE FROM FDSEmployee;
DELETE FROM WWS;

insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (1, 'Manager', 'Norine', 'Baglow', 'nbaglow0@hp.com', 'UYqkoIyltQoA');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (2, 'Manager', 'Baxie', 'Cannon', 'bcannon1@bing.com', 'Hv8Ea4');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (3, 'Manager', 'Derron', 'Tatchell', 'dtatchell2@stanford.edu', 'YTRNLX');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (4, 'Manager', 'Augustine', 'Sperwell', 'asperwell3@t-online.de', 'AyNgCpWQ');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (5, 'Manager', 'Margy', 'Bogeys', 'mbogeys4@php.net', '4ZJiIM');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (6, 'Manager', 'Fletcher', 'Burchnall', 'fburchnall5@google.com', '1cD6LWignKw');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (7, 'Manager', 'Guilbert', 'Ashleigh', 'gashleigh6@lycos.com', 'I8L9euQlTUK');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (8, 'Manager', 'Griswold', 'Bruhn', 'gbruhn7@mediafire.com', 'fq8mte9a09');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (9, 'Manager', 'Casi', 'Shimon', 'cshimon8@mail.ru', 'yNynEWNfR');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (10, 'Manager', 'Angelica', 'Drinkale', 'adrinkale9@latimes.com', 'C5qHLa0');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (11, 'Manager', 'Vikki', 'Overell', 'voverella@thetimes.co.uk', 'AlhAepDEdfH');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (12, 'Manager', 'Sybila', 'Longmate', 'slongmateb@globo.com', 'J89O7WR');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (13, 'Manager', 'Forster', 'Dawnay', 'fdawnayc@163.com', 'KwcAPtd');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (14, 'Manager', 'Silva', 'Ratcliff', 'sratcliffd@goo.gl', 'tWUFqVDEoBwp');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (15, 'Manager', 'Loraine', 'Fairholme', 'lfairholmee@cbc.ca', 'DlPfgCqBfOV');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (16, 'Manager', 'Sancho', 'Placidi', 'splacidif@sbwire.com', 'GnhWNx1HLU');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (17, 'Manager', 'Cammy', 'Pordall', 'cpordallg@sciencedirect.com', 'wFaYF2A63od');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (18, 'Manager', 'Lulita', 'Dimblebee', 'ldimblebeeh@cornell.edu', 'XR8YT3jkZ');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (19, 'Manager', 'Becca', 'Quoit', 'bquoiti@washingtonpost.com', 'nLVaYy8NdSJv');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (20, 'Manager', 'Nicky', 'Raff', 'nraffj@mit.edu', 'EvrYAyKeCdZ');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (21, 'Manager', 'Birgit', 'Elstub', 'belstubk@geocities.com', 'cMumSgSlq');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (22, 'Manager', 'Ali', 'Tapply', 'atapplyl@umn.edu', 'aqi6as0Bm');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (23, 'Manager', 'Haydon', 'Burford', 'hburfordm@washingtonpost.com', 't7vOc7ln');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (24, 'Manager', 'Maire', 'Birdfield', 'mbirdfieldn@godaddy.com', 'kzL60EoT');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (25, 'Manager', 'Tiff', 'Nudd', 'tnuddo@xinhuanet.com', 'F7M7Wo0Q9');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (26, 'Manager', 'Yvonne', 'Fossick', 'yfossickp@amazon.co.jp', 'yc8UTHy');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (27, 'Manager', 'Maribeth', 'Lewsey', 'mlewseyq@live.com', 'VXSoYQV');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (28, 'Manager', 'Augusto', 'Dessaur', 'adessaurr@fda.gov', 'RIErj3dt8G');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (29, 'Manager', 'Fletch', 'Mance', 'fmances@infoseek.co.jp', '15jebT');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (30, 'Manager', 'Alanah', 'Abramov', 'aabramovt@facebook.com', 'h4olV16FCN');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (31, 'Manager', 'Merrilee', 'Mardy', 'mmardyu@upenn.edu', 'U6KDbixs');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (32, 'Manager', 'Verney', 'Jope', 'vjopev@youku.com', 'tGvJcGH9W');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (33, 'Manager', 'Barry', 'Spindler', 'bspindlerw@lycos.com', 'QjmjJnvyZ');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (34, 'Manager', 'Elise', 'Warin', 'ewarinx@scientificamerican.com', 'm0lF9DwZE');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (35, 'Manager', 'Pippo', 'Cotsford', 'pcotsfordy@pen.io', '4FWjSFG2');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (36, 'Manager', 'Dannel', 'Defau', 'ddefauz@reference.com', 'oUx1goe');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (37, 'Manager', 'Roland', 'Urpeth', 'rurpeth10@pcworld.com', 'QwTP02ZvL');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (38, 'Manager', 'Agathe', 'Treneer', 'atreneer11@desdev.cn', 'SFJtswr1AM');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (39, 'Manager', 'Obediah', 'Mellon', 'omellon12@flavors.me', 'taxb0kwHRE');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (40, 'Manager', 'Ashly', 'Gillebert', 'agillebert13@soundcloud.com', '5JrG79eLi');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (41, 'Manager', 'Dasya', 'Aishford', 'daishford14@yelp.com', 'QrzjAld');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (42, 'Manager', 'Michell', 'Fidoe', 'mfidoe15@bloglovin.com', 'sCIGkThQKQ');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (43, 'Manager', 'Julie', 'Dawton', 'jdawton16@scientificamerican.com', 'Qk9vOO');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (44, 'Manager', 'Anetta', 'Keemar', 'akeemar17@homestead.com', 'eYEbRYP2');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (45, 'Manager', 'Pincus', 'Brombell', 'pbrombell18@java.com', 'pi5BetJvCs');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (46, 'Manager', 'Town', 'Fawks', 'tfawks19@quantcast.com', 'L4oYTnshp');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (47, 'Manager', 'Irving', 'Bonnier', 'ibonnier1a@tiny.cc', 'l1hk0Ju2QTQE');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (48, 'Manager', 'Ave', 'Adamczyk', 'aadamczyk1b@columbia.edu', 'SSow9loRKh3n');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (49, 'Manager', 'Chastity', 'Lepoidevin', 'clepoidevin1c@eventbrite.com', 'WpiNg9');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (50, 'Manager', 'Bertram', 'De Gowe', 'bdegowe1d@wufoo.com', 'MYtqPD5Ew');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (51, 'Rider', 'Margarethe', 'McWilliams', 'mmcwilliams0@t-online.de', 'h6hgYzcMtrw3');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (52, 'Rider', 'Ana', 'Youle', 'ayoule1@abc.net.au', 'VgpsNQj');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (53, 'Rider', 'Tiena', 'Lerohan', 'tlerohan2@is.gd', 'cUt2pCL');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (54, 'Rider', 'Bethany', 'Pagin', 'bpagin3@ocn.ne.jp', 'j67e9S');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (55, 'Rider', 'Dorette', 'Tingly', 'dtingly4@huffingtonpost.com', 'KugRZbhgEqHx');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (56, 'Rider', 'Timothy', 'Stanley', 'tstanley5@google.cn', 'DxZPLBp');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (57, 'Rider', 'Maren', 'Pachta', 'mpachta6@hatena.ne.jp', 'yDOHBY');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (58, 'Rider', 'Daron', 'Cleland', 'dcleland7@fema.gov', 'uw37YvSJzS6');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (59, 'Rider', 'Costanza', 'Pinsent', 'cpinsent8@myspace.com', '205RxF5XYu');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (60, 'Rider', 'Luise', 'Domanek', 'ldomanek9@amazon.com', '8dRd6d');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (61, 'Rider', 'Bridie', 'Kobpac', 'bkobpaca@va.gov', 'WSqjaa2VN');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (62, 'Rider', 'Lawry', 'Keson', 'lkesonb@prlog.org', '9bcnIJwLAz3');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (63, 'Rider', 'Janith', 'Swane', 'jswanec@hao123.com', 'GtNqyxMOBe9E');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (64, 'Rider', 'Raymond', 'Havill', 'rhavilld@vk.com', 'qGfzAVe');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (65, 'Rider', 'Abbi', 'Pendlebury', 'apendleburye@google.fr', 'eAUT1e6');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (66, 'Rider', 'Lambert', 'Dutton', 'lduttonf@hexun.com', '0UxtIX6ak');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (67, 'Rider', 'Curt', 'Clayfield', 'cclayfieldg@mapy.cz', '1nbNi9R');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (68, 'Rider', 'Isobel', 'McCorkindale', 'imccorkindaleh@bing.com', 'vdRvni7s4rK');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (69, 'Rider', 'Helsa', 'Bonnett', 'hbonnetti@a8.net', 'ud4p1N4M3xOu');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (70, 'Rider', 'Adair', 'Daelman', 'adaelmanj@blog.com', 'QflkcQEoQc');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (71, 'Rider', 'Rancell', 'Kilgallen', 'rkilgallenk@spotify.com', 'VfMpUmVkh6');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (72, 'Rider', 'Tabina', 'Meates', 'tmeatesl@yellowbook.com', 'iyC9AA');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (73, 'Rider', 'Cortie', 'Willoughway', 'cwilloughwaym@github.io', 'yiwzT7g');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (74, 'Rider', 'Lowell', 'Scoullar', 'lscoullarn@reuters.com', 'D7EZg6');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (75, 'Rider', 'Eben', 'Tester', 'etestero@goo.gl', 'BPHhgEFze9');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (76, 'Rider', 'Christan', 'Purvess', 'cpurvessp@ox.ac.uk', 'cKR72GVjAWGg');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (77, 'Rider', 'Nolie', 'Underwood', 'nunderwoodq@psu.edu', 'vV3fQtCK');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (78, 'Rider', 'Vladimir', 'Weaving', 'vweavingr@nytimes.com', '69hHCEboLazR');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (79, 'Rider', 'Lynnea', 'Audiss', 'laudisss@slashdot.org', 'znXYcFrKD');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (80, 'Rider', 'Vaughn', 'Sermin', 'vsermint@flavors.me', 'eR7RdYE9');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (81, 'Rider', 'Cori', 'L''Episcopi', 'clepiscopiu@cam.ac.uk', '36fqSf9NISZg');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (82, 'Rider', 'Arther', 'Anmore', 'aanmorev@opera.com', 'LE3NqFlNQ7Rr');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (83, 'Rider', 'Dulcia', 'Uebel', 'duebelw@marketwatch.com', 'zU7CgPHEA');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (84, 'Rider', 'Yanaton', 'Kupis', 'ykupisx@smugmug.com', 'zrn5ep9zUSN');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (85, 'Rider', 'Sayre', 'West', 'swesty@wix.com', 'RsuPNwe4l2I');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (86, 'Rider', 'Vinson', 'Aikman', 'vaikmanz@scientificamerican.com', 'MJT3VYaOrjeU');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (87, 'Rider', 'Katinka', 'Washtell', 'kwashtell10@nih.gov', '3BAaQfUJfIAi');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (88, 'Rider', 'Delano', 'Tocknell', 'dtocknell11@g.co', 'bzbI8m');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (89, 'Rider', 'Barris', 'Ossipenko', 'bossipenko12@elpais.com', 'ZGyuIkBc0Lxc');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (90, 'Rider', 'Grange', 'Dignan', 'gdignan13@goo.ne.jp', 'CZRgdFtX');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (91, 'Rider', 'Joni', 'Poluzzi', 'jpoluzzi14@altervista.org', 'MzTdvCjcj');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (92, 'Rider', 'Grata', 'Bendixen', 'gbendixen15@exblog.jp', '7kFg2wzGziA');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (93, 'Rider', 'Marlee', 'Roma', 'mroma16@sakura.ne.jp', 'YoOjyyfUq');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (94, 'Rider', 'Rancell', 'Gutman', 'rgutman17@intel.com', '9VJUFnM');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (95, 'Rider', 'Raina', 'Moylane', 'rmoylane18@sogou.com', 'c9gAy2EW');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (96, 'Rider', 'Reinald', 'Demke', 'rdemke19@tripod.com', 'yc0a5oWBai');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (97, 'Rider', 'Joyann', 'Sweeten', 'jsweeten1a@gravatar.com', '3aqfIS6L1tdH');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (98, 'Rider', 'Arlana', 'Muslim', 'amuslim1b@army.mil', 'YiOuCGhRhf');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (99, 'Rider', 'Petrina', 'Czadla', 'pczadla1c@hostgator.com', 'CPxkzcioDud');
insert into FDSEmployee (empid, emptype, emp_first_name, emp_last_name, email, emppassword) values (100, 'Rider', 'Sonnie', 'Hulland', 'shulland1d@bizjournals.com', '9nHFwko92a3D');

INSERT INTO Manager VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30),(31),(32),(33),(34),(35),(36),(37),(38),(39),(40),(41),(42),(43),(44),(45),(46),(47),(48),(49),(50);

INSERT INTO Rider VALUES (51,false),(52,false),(53,false),(54,false),(55,false),(56,false),(57,false),(58,false),(59,false),(60,false),(61,false),(62,false),(63,false),(64,false),(65,false),(66,false),(67,false),(68,false),(69,false),(70,false);
INSERT INTO Rider VALUES (71,true),(72,true),(73,true),(74,true),(75,true),(76,true),(77,true),(78,true),(79,true),(80,true);

INSERT INTO WorkShift VALUES (0, false,false,false,false,false,false,false,false,false,false,false,false,true);
INSERT INTO WorkShift VALUES (1, true, true, true, true, false, true, true, true, true, false, false, false, true);
INSERT INTO WorkShift VALUES (2, false, true, true, true, true, false, true, true, true, true, false, false, true);
INSERT INTO WorkShift VALUES (3, false, false, true, true, true, true, false, true, true, true, true, false, true);
INSERT INTO WorkShift VALUES (4, false, false, false, true, true, true, true, false, true, true, true, true, true);

insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (5, false, false, false, false, true, true, false, false, true, false, true, false);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (6, false, true, false, false, true, false, true, true, true, false, false, false);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (7, false, false, true, true, true, true, false, false, true, false, true, true);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (8, true, false, true, true, true, false, false, false, true, true, false, true);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (9, true, true, false, false, true, true, false, false, true, true, false, false);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (10, true, true, false, false, true, false, true, true, true, false, true, false);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (11, false, false, true, true, false, true, true, false, true, true, false, false);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (12, true, true, false, false, false, false, true, false, false, true, true, true);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (13, false, false, true, false, true, false, false, false, false, false, true, false);
insert into WorkShift (wsid, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12) values (14, true, false, false, true, true, false, true, true, false, false, false, true);

INSERT INTO WWS VALUES (51,1,1,1,1,1,0,0),(52,1,1,1,1,1,0,0),(53,1,1,1,1,1,0,0),(54,1,1,1,1,1,0,0),(55,1,1,1,1,1,0,0);
INSERT INTO WWS VALUES (56,0,0,1,1,1,1,1),(57,0,0,1,1,1,1,1),(58,0,0,1,1,1,1,1),(59,0,0,1,1,1,1,1),(60,0,0,1,1,1,1,1);
INSERT INTO WWS VALUES (61,4,4,4,4,4,0,0),(62,4,4,4,4,4,0,0),(63,4,4,4,4,4,0,0),(64,4,4,4,4,4,0,0),(65,4,4,4,4,4,0,0);
INSERT INTO WWS VALUES (66,0,0,4,4,4,4,4),(67,0,0,4,4,4,4,4),(68,0,0,4,4,4,4,4),(69,0,0,4,4,4,4,4),(70,0,0,4,4,4,4,4);

insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (71, 5, 6, 12, 8, 8, 8, 12);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (72, 8, 12, 9, 14, 14, 13, 10);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (73, 11, 12, 12, 10, 14, 5, 7);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (74, 13, 11, 14, 5, 12, 7, 9);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (75, 5, 12, 14, 11, 8, 13, 11);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (76, 6, 10, 8, 7, 11, 11, 5);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (77, 13, 14, 9, 10, 14, 12, 8);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (78, 6, 6, 10, 14, 10, 14, 8);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (79, 6, 7, 9, 14, 12, 6, 14);
insert into WWS (empid, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) values (80, 8, 5, 14, 10, 9, 6, 6);